preserve_hierarchy: true

files:
  - source: /**/src/main/res/values/strings.xml
    translation: "%original_path%-%android_code%/%original_file_name%"
    type: android
    ignore:
      - /analyze/**
      - /**/build/**
    languages_mapping:
      android_code:
        he: iw
        id: in
        yi: ji