preserve_hierarchy: 1
files:
  - source: /**/src/main/res/values/strings.xml
    ignore:
      - /analyze/**
      - /**/build/**
    translation: /%original_path%-%android_code%/%original_file_name%
    type: android
